channels:
- conda-forge
dependencies:
- jupyterlab
- nodejs
- notebook
- nbconvert
- ipykernel
- ipywidgets
- ipyleaflet
- widgetsnbextension
- bqplot
- matplotlib
- pandas
- python
- scikit-image
- scikit-learn
- seaborn
- sympy
- xwidgets
